---
name: Continuous Integration

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  vale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: errata-ai/vale-action@reviewdog
        with:
          fail_on_error: true
          reporter: github-check
          vale_flags: "--glob=*.{md,txt}"
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
  detect-changes:
    outputs:
      java: ${{ steps.changes.outputs.java }}
      python: ${{ steps.changes.outputs.python }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            java:
              - 'java/**'
            python:
              - 'python/**'
  java-build:
    needs: [vale, detect-changes]
    if: needs.detect-changes.outputs.java == 'true'
    uses: ./.github/workflows/java_build.yaml
  python-test:
    needs: [vale, detect-changes]
    if: needs.detect-changes.outputs.python == 'true'
    uses: ./.github/workflows/python_test.yaml
  ci-status-check:
    name: Continuous Integration Status Check
    needs: [java-build, python-test]
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Exit successfully
        run: exit 0
